#!/bin/bash

echo "For this fork of plink-ng, the modules gcc/4.9.2 and ATLAS/3.10.3 should be loaded before running this script on uppmax"
echo -c "waiting for 5 seconds..."
sleep 5
echo "done"

# Download and verify zlib
EXPECTEDCHECKSUM=a4d316c404ff54ca545ea71a27af7dbc29817088
curl -O http://zlib.net/zlib-1.2.8.tar.gz
CHECKSUM=$(shasum zlib-1.2.8.tar.gz | cut -b-40)
if [ "$EXPECTEDCHECKSUM" != "$CHECKSUM" ]; then
    echo "Zlib checksum verification failure"
    exit 1
fi;

# Unpack and compile zlib
tar -xzvf zlib-1.2.8.tar.gz
cd zlib-1.2.8
./configure
make

# Compile
cd ..
make -f Makefile.std plink
